// ============================================================
// GizmoHub - Product Data (Shared across pages)
// ============================================================

const products = [
    {
        id: 1,
        name: "iPhone 15 Pro Max",
        category: "phones",
        price: 1199,
        originalPrice: 1399,
        discount: 14,
        description: "The most advanced iPhone ever with A17 Pro chip, 6.7\" Super Retina XDR display, titanium design, and 48MP main camera with 5x telephoto zoom.",
        rating: 4.9,
        reviews: 458,
        image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&q=80",
        badge: "bestseller",
        isNew: false
    },
    {
        id: 2,
        name: "Samsung Galaxy S24 Ultra",
        category: "phones",
        price: 1099,
        originalPrice: 1299,
        discount: 15,
        description: "The ultimate Galaxy flagship with built-in S Pen, 200MP main camera, Snapdragon 8 Gen 3, and Galaxy AI for intelligent photo editing.",
        rating: 4.8,
        reviews: 342,
        image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
        badge: "new",
        isNew: true
    },
    {
        id: 3,
        name: "Google Pixel 8 Pro",
        category: "phones",
        price: 899,
        originalPrice: 999,
        discount: 10,
        description: "AI-powered smartphone with Tensor G3 chip, advanced computational photography, 6.7\" LTPO OLED display, and 7 years of OS updates.",
        rating: 4.7,
        reviews: 256,
        image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
        badge: null,
        isNew: false
    },
    {
        id: 4,
        name: "AirPods Pro 2",
        category: "audio",
        price: 199,
        originalPrice: 249,
        discount: 20,
        description: "Active Noise Cancellation with adaptive transparency mode, personalized spatial audio, USB-C charging case, and 6 hours of listening time.",
        rating: 4.8,
        reviews: 867,
        image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400&q=80",
        badge: "bestseller",
        isNew: false
    },
    {
        id: 5,
        name: "Sony WH-1000XM5",
        category: "audio",
        price: 349,
        originalPrice: 399,
        discount: 13,
        description: "Industry-leading noise cancellation with 8 microphones, 30-hour battery life, multipoint Bluetooth connection, and crystal-clear hands-free calling.",
        rating: 4.9,
        reviews: 1243,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
        badge: "new",
        isNew: true
    },
    {
        id: 6,
        name: "Apple Watch Series 9",
        category: "watches",
        price: 399,
        originalPrice: 429,
        discount: 7,
        description: "The ultimate smartwatch with S9 chip, double-tap gesture, brighter Always-On display, advanced health features including blood oxygen and ECG.",
        rating: 4.8,
        reviews: 567,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
        badge: "new",
        isNew: true
    },
    {
        id: 7,
        name: "Samsung Galaxy Watch 6",
        category: "watches",
        price: 299,
        originalPrice: 349,
        discount: 14,
        description: "Advanced health monitoring with body composition analysis, sapphire crystal glass, Wear OS powered by Samsung, and sleep coaching insights.",
        rating: 4.6,
        reviews: 234,
        image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400&q=80",
        badge: "sale",
        isNew: false
    },
    {
        id: 8,
        name: "65W GaN Fast Charger",
        category: "chargers",
        price: 39,
        originalPrice: 59,
        discount: 34,
        description: "Super fast 65W charging with dual USB-C ports, GaN III technology for compact size, intelligent power distribution, and universal compatibility.",
        rating: 4.7,
        reviews: 612,
        image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80",
        badge: "bestseller",
        isNew: false
    },
    {
        id: 9,
        name: "Power Bank 20000mAh",
        category: "chargers",
        price: 49,
        originalPrice: 79,
        discount: 38,
        description: "High-capacity 20000mAh power bank with dual USB-C PD ports, 22.5W fast charging, built-in cable, and LED power indicator display.",
        rating: 4.5,
        reviews: 498,
        image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&q=80",
        badge: null,
        isNew: false
    },
    {
        id: 10,
        name: "DJI Mini 3 Pro",
        category: "drones",
        price: 759,
        originalPrice: 899,
        discount: 16,
        description: "Compact sub-249g drone with 4K HDR video, 48MP photos, 34-minute flight time, tri-directional obstacle avoidance, and intelligent shooting modes.",
        rating: 4.8,
        reviews: 189,
        image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&q=80",
        badge: "new",
        isNew: true
    },
    {
        id: 11,
        name: "Galaxy Buds2 Pro",
        category: "audio",
        price: 179,
        originalPrice: 229,
        discount: 22,
        description: "Premium wireless earbuds with intelligent ANC, 360 Audio, Hi-Fi 24bit sound, IPX7 water resistance, and seamless Galaxy ecosystem integration.",
        rating: 4.6,
        reviews: 334,
        image: "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=400&q=80",
        badge: "sale",
        isNew: false
    },
    {
        id: 12,
        name: "iPhone 15 Silicone Case",
        category: "accessories",
        price: 49,
        originalPrice: 69,
        discount: 29,
        description: "Premium silicone case with MagSafe support, soft microfiber lining, raised edges for screen and camera protection, and silky soft-touch finish.",
        rating: 4.6,
        reviews: 520,
        image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&q=80",
        badge: "bestseller",
        isNew: false
    },
    {
        id: 13,
        name: "Samsung Galaxy S26 Ultra",
        category: "phones",
        price: 1199,
        originalPrice: 1399,
        discount: 14,
        description: "Latest 2025 flagship with 200MP main camera, Galaxy AI suite, Snapdragon 8 Elite processor, 6.8\" Dynamic AMOLED 2X, and titanium frame.",
        rating: 4.9,
        reviews: 287,
        image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
        badge: "sale",
        isNew: true
    },
    {
        id: 14,
        name: "Samsung Galaxy S25 Ultra",
        category: "phones",
        price: 999,
        originalPrice: 1299,
        discount: 23,
        description: "Premium Galaxy with built-in S Pen, titanium frame, Snapdragon 8 Gen 4 processor, 200MP camera system, and advanced Galaxy AI photo editing.",
        rating: 4.8,
        reviews: 412,
        image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
        badge: "sale",
        isNew: false
    },
    {
        id: 15,
        name: "iPhone 16 Pro Max",
        category: "phones",
        price: 1199,
        originalPrice: 1399,
        discount: 14,
        description: "A18 Pro chip with Apple Intelligence, 6.9\" Super Retina XDR display, titanium design, and 48MP Fusion camera system.",
        rating: 4.9,
        reviews: 521,
        image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&q=80",
        badge: "new",
        isNew: true
    },
    {
        id: 16,
        name: "iPhone 16 Pro",
        category: "phones",
        price: 999,
        originalPrice: 1199,
        discount: 17,
        description: "Pro camera system with 5x optical zoom, A18 Pro chip, 6.3\" display, Camera Control button, and titanium grade 5 design.",
        rating: 4.8,
        reviews: 678,
        image: "https://images.unsplash.com/photo-1592286927505-1def25115558?w=400&q=80",
        badge: "new",
        isNew: true
    },
    {
        id: 17,
        name: "iPhone 16 Plus",
        category: "phones",
        price: 899,
        originalPrice: 1099,
        discount: 18,
        description: "Larger 6.7\" Super Retina XDR display with A18 chip, all-day battery life up to 27 hours, and 48MP main camera.",
        rating: 4.7,
        reviews: 445,
        image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
        badge: "sale",
        isNew: true
    },
    {
        id: 18,
        name: "iPhone 16",
        category: "phones",
        price: 799,
        originalPrice: 999,
        discount: 20,
        description: "The latest iPhone with Dynamic Island, 6.1\" Super Retina XDR display, A18 chip, Camera Control, and 48MP Fusion camera.",
        rating: 4.7,
        reviews: 891,
        image: "https://images.unsplash.com/photo-1592286927505-1def25115558?w=400&q=80",
        badge: "bestseller",
        isNew: true
    },
    {
        id: 19,
        name: "iPhone 17 Pro Max",
        category: "phones",
        price: 1299,
        originalPrice: 1499,
        discount: 13,
        description: "Next-gen A19 Pro chip with revolutionary AI features, 6.9\" Super Retina XDR display, 48MP Fusion camera with advanced computational photography.",
        rating: 4.9,
        reviews: 156,
        image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&q=80",
        badge: "new",
        isNew: true
    },
    {
        id: 20,
        name: "iPhone 17 Pro",
        category: "phones",
        price: 1099,
        originalPrice: 1299,
        discount: 15,
        description: "ProMotion 120Hz display with always-on technology, A19 Pro chip, titanium design, and 5x optical zoom camera system.",
        rating: 4.9,
        reviews: 203,
        image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
        badge: "new",
        isNew: true
    },
    {
        id: 21,
        name: "iPhone 17 Air",
        category: "phones",
        price: 999,
        originalPrice: 1199,
        discount: 17,
        description: "Ultra-thin 5.4mm design with stunning edge-to-edge display, all-day battery life, and the latest A19 chip in a featherlight form.",
        rating: 4.8,
        reviews: 178,
        image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
        badge: "sale",
        isNew: true
    },
    {
        id: 22,
        name: "iPhone 17",
        category: "phones",
        price: 899,
        originalPrice: 1099,
        discount: 18,
        description: "The perfect balance of performance and value with A19 chip, improved dual-camera system, and all-day battery in vibrant new colors.",
        rating: 4.8,
        reviews: 312,
        image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&q=80",
        badge: "bestseller",
        isNew: true
    }
];
